Typo

diff --git a/limeyum b/limeyum
--- a/limeyum
+++ b/limeyum
@@ -47,8 +47,8 @@ fi
 # --- Create a new project ---
 if [[ $STARTINGOPTION == 2 ]]; then
     read -p "Project Name: " PROJNAME
-    mkdir -p "$home/projects/$PROJNAME"
-    cd "./projects/$PROJNAME" || { echo "${RED}Could not create project.${NC}"; exit 1; }
+    mkdir -p "${SCRIPT_DIR}/projects/${PROJNAME}"
+    cd "${SCRIPT_DIR}/projects/$PROJNAME" || { echo "${RED}Could not create project.${NC}"; exit 1; }
     echo "${GREEN}[+] Project $PROJNAME created.${NC}"
     read -p "Initial Target IP: " TARGETIP
     read -p "Initial Target URL: " TARGETURL
